---

# tasks file for osp.servers
- name: Create a new instance and attaches to a network and passes metadata to the instance
  os_server:
        state: present
        cloud: ospcloud
        name: first-instance-1
        image: rhel-guest
        key_name: ansible_ssh
        timeout: 200
        flavor: m2.small
        network: ext_network
        auto_ip: yes
        security_groups:
          - apps

   
- name: Wait 600 seconds for target connection to become reachable/usable
  wait_for_connection:
